const ProductConstants = Object.freeze({
	ALL_PRODUCT_REQUEST: "ALL_PRODUCT_REQUEST",
	ALL_PRODUCT_SUCCESS: "ALL_PRODUCT_SUCCESS",
	ALL_PRODUCT_FAIL: "ALL_PRODUCT_FAIL",
	CLEAR_ERRORS: "CLEAR_ERRORS",

	REVIEW_FORM_UPDATED: "REVIEW_FORM_UPDATED",
	PRODUCT_REVIEW_FETCHED: "PRODUCT_REVIEW_FETCHED",
});

export default ProductConstants;
