const ProductConstants = Object.freeze({
	ALL_PRODUCT_REQUEST: "ALL_PRODUCT_REQUEST",
	ALL_PRODUCT_SUCCESS: "ALL_PRODUCT_SUCCESS",
	ALL_PRODUCT_FAIL: "ALL_PRODUCT_FAIL",
	CLEAR_ERRORS: "CLEAR_ERRORS",
});

export default ProductConstants;
