const UserConstants = Object.freeze({
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAIL: "LOGIN_FAIL",

	LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
	LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
	LOAD_USER_FAIL: "LOAD_USER_FAIL",

	REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
	REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
	REGISTER_USER_FAIL: "REGISTER_USER_FAIL",

	LOGOUT_REQUEST: "LOGOUT_REQUEST",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
	LOGOUT_FAIL: "LOGOUT_FAIL",

	UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
	UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
	UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

	FOLLOW_USER_REQUEST: "FOLLOW_USER_REQUEST",
	FOLLOW_USER_SUCCESS: "FOLLOW_USER_SUCCESS",
	FOLLOW_USER_FAILURE: "FOLLOW_USER_FAILURE",

	UNFOLLOW_USER_REQUEST: "UNFOLLOW_USER_REQUEST",
	UNFOLLOW_USER_SUCCESS: "UNFOLLOW_USER_SUCCESS",
	UNFOLLOW_USER_FAILURE: "UNFOLLOW_USER_FAILURE",

	ADD_TO_WISHLIST_REQUEST: "ADD_TO_WISHLIST_REQUEST",
	ADD_TO_WISHLIST_SUCCESS: "ADD_TO_WISHLIST_SUCCESS",
	ADD_TO_WISHLIST_FAILURE: "ADD_TO_WISHLIST_FAILURE",

	REMOVE_FROM_WISHLIST_REQUEST: "REMOVE_FROM_WISHLIST_REQUEST",
	REMOVE_FROM_WISHLIST_SUCCESS: "REMOVE_FROM_WISHLIST_SUCCESS",
	REMOVE_FROM_WISHLIST_FAILURE: "REMOVE_FROM_WISHLIST_FAILURE",

	CLEAR_ERRORS: "CLEAR_ERRORS",
});

export default UserConstants;
