const UserConstants = Object.freeze({
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAIL: "LOGIN_FAIL",

	LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
	LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
	LOAD_USER_FAIL: "LOAD_USER_FAIL",

	REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
	REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
	REGISTER_USER_FAIL: "REGISTER_USER_FAIL",

	LOGOUT_REQUEST: "LOGOUT_REQUEST",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
	LOGOUT_FAIL: "LOGOUT_FAIL",

	CLEAR_ERRORS: "CLEAR_ERRORS",
});

export default UserConstants;
